### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by macMikey** [miyako/tree-sitter-4dm#1]
Installing “tree-sitter-4dm@1.7.0” failed.Hide output…
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/me/.atom/packages/tree-sitter-4dm/node_modules/abbrev/package.json'
Emitted 'error' event at:
    at WriteStream.onerror (_stream_readable.js:696:12)
    at WriteStream.emit (events.js:182:13)
    at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:211:14
    at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:169:20)

**Comment by miyako** [comment]
you are not supposed to install tree-sitter parsers directly.

stop spamming please.

**Comment by macMikey** [comment]
Miyako, I'm not spamming.  I went into Atom, opened the package manager, saw a bunch of 4D packages, and installed them.
I got errors on several of them, and I reported the errors.
If you are not supposed to install the tree-sitter parsers, then why do they show up in the package manager inside of Atom?

**Comment by miyako** [comment]
Posting error logs with no context to a discussion board definitely looks like spamming.

I installed using 1.47.0, added modules from preferences, installed the packages and see no errors. So don't jump to conclusion that the "error speaks for itself", It doesn't.

<img width="1104" alt="スクリーンショット 2020-06-02 2 53 39" src="https://user-images.githubusercontent.com/1725068/83438400-59571280-a47c-11ea-99a6-d7de0dd4a893.png">
.

**Comment by miyako** [comment]
As for the tree-sitter parsers, it is critical that they are published on ``npm`` but for ``apm``, I guess it is safer to hide them.

Unpublished:

* tree-sitter-4dm
* tree-sitter-4dxml
* tree-sitter-4djson

**Comment by miyako** [comment]
I think you should uninstall all new packages until you get rid of errors.

After that, install one-by-one, to pin down which module generates an error.

Normally you can install all of them at once, but it seems like your installation has issues.

**Comment by macMikey** [comment]
sorry that it looked like spamming.  since each of the repos is separate, I just copied and pasted the errors for each of them onto their repo issues.
thank you for the help resolving it.
